[package]
name = "portctl"
version = "0.1.0"
edition = "2024"
description = "Cross-platform CLI to find, kill, and list processes occupying network ports (Linux / macOS / Windows)"
license = "MIT"                    
repository = "https://github.com/RowanCole/portctl"
homepage = "https://github.com/RowanCole/portctl"   
documentation = "https://docs.rs/portctl"           
readme = "README.md"                               
keywords = ["cli", "port"]                          


[[bin]]
name = "portctl"
path = "src/main.rs"

[features]
default = ["en"]
zh = []
en = []

[dependencies]
clap = { version = "4", features = ["derive"] }
netstat2 = "0.11"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
libproc = "0.14"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_System_Threading"] }
